### ISSUE TITLE
There should be a way to safely stop the bacground threads

### ISSUE THREAD

**Issue by ymolists** [giltene/PauselessHashMap#3]
Hi Gil.

I tried to play with this Pauseless HashMap and its barking at me (. It looks like there is no way to cleanly stop those 2 threads running in the background and maybe JMH does not like that very well ???

thread dump http://pastebin.com/CWSqZpfX
jmh based benchmark http://pastebin.com/NUN4vDet

If i replace line 34 with java.util.HashMap everything works fine.

p.s.
I sent this to the list since this is not necessarily the hashMap. Even if i kill the test the forked java process by jmh is still running. However there should be a way to safely stop the bacground threads.

Thanks.

**Comment by giltene** [comment]
The backgroundResizers threads were not daemons, so they keep the JVM alive unless it explicitly exits (which I guess junit does but jmh doesn't). I now made backgroundResizers into daemons with change https://github.com/giltene/PauselessHashMap/commit/4b57b502d0ef6ff82172cc19d9e650d31e355132. Can you try it again?

**Comment by ymolists** [comment]
It seems that this issue is fixed now. Thank you )))
